version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bbox_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bbox_library
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: bbox-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bbox_library
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: bbox-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  # frontend:
  #   build: ./frontend
  #   container_name: bbox-frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:80"

volumes:
  db_data:
